// Paul Acts Atlas v7 — Simple Focus UI
(() => {
  const main = document.querySelector('.main');
  const content = document.querySelector('.content');
  const hero = document.querySelector('.hero');
  if (!main || !content || !hero || document.getElementById('simpleTopbar')) return;
  hero.innerHTML = `<div class="hero-inner"><div class="eyebrow">ACTS × PAUL · SIMPLE MODE</div><h1>一條路，看懂《使徒行傳》。</h1><p>先記四幕、八個節點、五個時間數字；細節需要時再打開。畫面只保留你當下要學的東西。</p><div class="hero-route"><span>耶路撒冷</span><span class="line"></span><span>大馬士革</span><span class="line"></span><span>安提阿</span><span class="line"></span><span>以弗所</span><span class="line"></span><span>哥林多</span><span class="line"></span><span>羅馬</span></div></div>`;
  const topbar=document.createElement('div');topbar.id='simpleTopbar';topbar.className='simple-topbar';topbar.innerHTML=`<div class="simple-topbar-inner"><div class="simple-brand">使徒行傳一條線 <small>PAUL ATLAS v7</small></div><nav class="simple-nav" aria-label="主要導覽"><button class="active" data-view="home">總覽</button><button data-view="map">路程</button><button data-view="acts">章節</button><button data-view="bookreader">書信</button><button data-view="quiz">測驗</button><button data-view="more">更多</button></nav></div>`;main.before(topbar);
  const home=document.createElement('div');home.className='simple-home active';home.id='simpleHome';home.innerHTML=`<div class="simple-home-wrap"><div class="simple-title"><div><div class="eyebrow">先背骨架，再補細節</div><h2>整卷只先記這四幕</h2></div><p>第一次打開網站，只看這一頁就夠。會了再進路程、章節、書信。</p></div><div class="four-acts"><button class="act-card" data-ch="1"><b>徒 1–7</b><strong>耶路撒冷</strong><span>聖靈降臨 → 教會建立 → 司提反</span></button><button class="act-card" data-ch="8"><b>徒 8–12</b><strong>福音向外</strong><span>撒瑪利亞 → 掃羅歸信 → 安提阿</span></button><button class="act-card" data-ch="13"><b>徒 13–20</b><strong>三次宣教</strong><span>小亞細亞 → 歐洲 → 以弗所核心</span></button><button class="act-card" data-ch="21"><b>徒 21–28</b><strong>一路到羅馬</strong><span>被捕 → 該撒利亞 → 船難 → 羅馬</span></button></div><div class="main-line"><div class="main-line-head"><h3>保羅主線｜八個節點</h3><span>點任何一站 → 直接進相關章節</span></div><div class="route-steps"><button class="route-step" data-ch="9"><i>1</i><b>大馬士革</b><small>徒9<br>歸信</small></button><button class="route-step" data-ch="11"><i>2</i><b>安提阿</b><small>徒11<br>基地</small></button><button class="route-step" data-ch="13"><i>3</i><b>第一次</b><small>徒13–14<br>外邦</small></button><button class="route-step" data-ch="15"><i>4</i><b>會議</b><small>徒15<br>律法議題</small></button><button class="route-step" data-ch="16"><i>5</i><b>第二次</b><small>徒16–18<br>進歐洲</small></button><button class="route-step" data-ch="19"><i>6</i><b>第三次</b><small>徒19–20<br>以弗所</small></button><button class="route-step" data-ch="24"><i>7</i><b>該撒利亞</b><small>徒23–26<br>被囚2年</small></button><button class="route-step" data-ch="28"><i>8</i><b>羅馬</b><small>徒27–28<br>抵達終點</small></button></div></div><div class="memory-five"><div><strong>3年</strong><span>歸信後約三年第一次上耶路撒冷</span></div><div><strong>14年</strong><span>加2:1 的時間節點，不是住同地14年</span></div><div><strong>18月</strong><span>哥林多（徒18:11）</span></div><div><strong>2年</strong><span>該撒利亞被囚</span></div><div><strong>2年</strong><span>羅馬租屋傳道</span></div></div><div class="simple-actions"><button class="primary" data-go="map">▶ 看宣教路程</button><button data-go="acts">📖 選徒1–28章</button><button data-go="bookreader">✉️ 看書信</button></div><p class="focus-note">年代控制台、城市照片、皇帝背景、書信飛線、完整總表全部保留在「更多」，只是先藏起來。</p></div>`;
  const advanced=document.createElement('div');advanced.className='advanced-hub';advanced.id='advancedHub';advanced.innerHTML=`<div class="simple-title"><div><div class="eyebrow">ADVANCED</div><h2>深入資料</h2></div><p>只有真的要查細節時再進來，不干擾主線記憶。</p></div><div class="advanced-grid"><button class="advanced-card" data-advanced="fourteen"><b>14年釐清</b><span>三年、十四年到底怎麼算</span></button><button class="advanced-card" data-advanced="timeline"><b>保羅時間軸</b><span>按年份看生平</span></button><button class="advanced-card" data-advanced="chronology"><b>年代控制台</b><span>年份 × 皇帝 × 章節 × 書信</span></button><button class="advanced-card" data-advanced="scenes"><b>城市實景</b><span>大馬士革、以弗所、哥林多</span></button><button class="advanced-card" data-advanced="connections"><b>書信飛線</b><span>寫信地 → 收信地</span></button><button class="advanced-card" data-advanced="cinema"><b>電影時間長廊</b><span>關鍵章節沉浸場景</span></button><button class="advanced-card" data-advanced="empire"><b>羅馬背景</b><span>皇帝、行省、殖民市</span></button><button class="advanced-card" data-advanced="letters"><b>完整書信總表</b><span>所有欄位一次查</span></button><button class="advanced-card" data-advanced="sources"><b>資料說明</b><span>年代與來源註記</span></button></div>`;
  content.prepend(advanced);content.prepend(home);
  function hideAll(){document.querySelectorAll('.section').forEach(x=>x.classList.remove('simple-visible'));home.classList.remove('active');advanced.classList.remove('active')}
  function activeNav(view){document.querySelectorAll('.simple-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view))}
  window.simpleOpen=function(view,scroll=true){hideAll();if(view==='home')home.classList.add('active');else if(view==='more')advanced.classList.add('active');else document.getElementById(view)?.classList.add('simple-visible');activeNav(view);if(scroll)window.scrollTo({top:0,behavior:'smooth'});if(view==='map'&&typeof setJourney==='function')setJourney(typeof activeJourney==='string'?activeJourney:'j1')}
  window.showAdvanced=function(id){hideAll();const el=document.getElementById(id);if(!el)return;el.classList.add('simple-visible');el.querySelector('.advanced-back')?.remove();const back=document.createElement('div');back.className='advanced-back';back.innerHTML='<button type="button">← 回深入資料</button>';el.prepend(back);back.querySelector('button').addEventListener('click',()=>simpleOpen('more'));activeNav('more');window.scrollTo({top:0,behavior:'smooth'})}
  document.querySelectorAll('.simple-nav button').forEach(b=>b.addEventListener('click',()=>simpleOpen(b.dataset.view)));
  document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>simpleOpen(b.dataset.go)));
  document.querySelectorAll('.advanced-card').forEach(b=>b.addEventListener('click',()=>showAdvanced(b.dataset.advanced)));
  document.querySelectorAll('[data-ch]').forEach(b=>b.addEventListener('click',()=>{const ch=Number(b.dataset.ch);simpleOpen('acts',false);if(typeof showCh==='function')showCh(ch);setTimeout(()=>document.getElementById('acts')?.scrollIntoView({behavior:'smooth',block:'start'}),20)}));
  simpleOpen('home',false);
})();